service: tieboutworld
provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: ap-northeast-2
  memorySize: 128
functions:
  app:
    handler: lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true
plugins:
  - serverless-domain-manager

custom:
  customDomain:
    domainName: www.tieboutworld.com
    basePath: ""
    stage: ${self:provider.stage}
    createRoute53Record: true
    endpointType: "regional"
    hostedZoneId: Z042801823O6VAT4AFTDW
